### ISSUE TITLE
Fails to build mirage-console-unix library

### ISSUE THREAD

**Issue by talex5** [mirage/mirage-console#36]
Example Travis output:

https://travis-ci.org/talex5/mirage-dev/builds/53529612

    ...
    Building mirage-console.dev:
    make
    make install
    Installing mirage-console.dev.
    Building vchan.2.0.2:
    ./configure
    make
    make install
    Installing vchan.2.0.2.
    Building tcpip.dev:
    ./configure --prefix /home/travis/.opam/system --enable-xen
    make
    make install
    [ERROR] The compilation of tcpip.dev failed.
    # ocamlfind: Package `mirage-console.unix' not found

Probably related to the recent `xenctrl` change.

**Comment by avsm** [comment]
Testing a fix in #37

**Comment by avsm** [comment]
@talex5 : I'm not sure where this error is from:
https://travis-ci.org/avsm/mirage-console/jobs/53547043#L889

Why is MiniOS' blkfront being compiled at all?

**Comment by talex5** [comment]
It's just a standard Mini-OS build (includes all the default stuff). We rely on the linker to ignore the bits we don't need.

No idea why it doesn't find the file. It's including the right directory:

    # gcc -DCONFIG_START_NETWORK -DCONFIG_SPARSE_BSS -DCONFIG_BLKFRONT -DCONFIG_NETFRONT -DCONFIG_KBDFRONT -DCONFIG_FBFRONT -DCONFIG_CONSFRONT -DCONFIG_XENBUS -nostdinc -isystem /usr/lib/gcc/x86_64-linux-gnu/4.6/include -fno-builtin -Wall -Werror -Wredundant-decls -Wno-format -Wno-redundant-decls -Wformat -fno-stack-protector -fgnu89-inline -Wstrict-prototypes -Wnested-externs -Wpointer-arith -Winline -O3 -fno-tree-loop-distribute-patterns -D__INSIDE_MINIOS__ -m64 -mno-red-zone -fno-reorder-blocks -fno-stack-protector -fno-asynchronous-unwind-tables
    -isystem /home/travis/.opam/system/build/mirage-xen-minios.0.7.0/xen-minios-v0.6/extras/mini-os/../../extras/mini-os/include -D__MINIOS__ -D__XEN_INTERFACE_VERSION__=0x00030205 
    -isystem /home/travis/.opam/system/build/mirage-xen-minios.0.7.0/xen-minios-v0.6/extras/mini-os/../../extras/mini-os/arch/x86/include
    -isystem /home/travis/.opam/system/build/mirage-xen-minios.0.7.0/xen-minios-v0.6/extras/mini-os/../../extras/mini-os/arch/x86/include/x86_64 
    -c -o /home/travis/.opam/system/build/mirage-xen-minios.0.7.0/xen-minios-v0.6/extras/mini-os/blkfront.o /home/travis/.opam/system/build/mirage-xen-minios.0.7.0/xen-minios-v0.6/extras/mini-os/blkfront.c

(`/home/travis/.opam/system/build/mirage-xen-minios.0.7.0/xen-minios-v0.6/extras/mini-os/../../extras/mini-os/arch/x86/include` should contain `os.h`)

**Comment by talex5** [comment]
In any case, nothing has changed in Mini-OS for months. Try building again? Travis isn't building new branches for me at all, so maybe something's broken there.

**Comment by avsm** [comment]
Indeed, I can't reproduce it locally either.  Triggering a rebuild.

**Comment by avsm** [comment]
And failed again. Hrm, why on earth is our console the most complex to build anyway :)

**Comment by talex5** [comment]
I see that only the Travis test with xenctrl present is failing. Mini-OS is building in the other cases.

**Comment by avsm** [comment]
So it must be the `libxen-dev` headers interfering, as those are the depexts involved.

**Comment by avsm** [comment]
Aha, I bet this is because of some rsync option changing in OPAM 1.2.1, causing symlinks to not be properly copied in. Testing OPAM 1.2.0 vs 1.2.1 now.

**Comment by avsm** [comment]
Found the problem.  We're setting `EXTRA_DEPS` from the Travis scripts, and this leaks into the MiniOS build environment. mirage/mirage-xen-minios#15
